# Generated by Django 4.2.7 on 2023-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_studentId', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default='c00x', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=255),
        ),
    ]
