# Generated by Django 4.2.7 on 2023-12-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_date_added_attendance_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='mentor_name',
        ),
    ]
